version: '3.8'
services:
  db:
    container_name: postgres-latest
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes: 
      - .postgres:/var/lib/postgresql/data
  pgadmin:
      container_name: pgadmin4
      image: dpage/pgadmin4:latest
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      ports:
        - '${PGADMIN_PORT}:80'
volumes:
  db:
    driver: local
